### ISSUE TITLE
Further details on the labelling process

### ISSUE THREAD

**Issue by jambo6** [sujunhao/RENET2#2]
Hello, I had a few questions on the sentence labelling process. 

I'm looking at `abs_data/1st_ann`. Am I right in thinking:

1. Genes and diseases are extracted from the abstracts.
2. If a sentence contains both a gene and a disease, the relationship is annotated as either `0, 0.5, 1` by an expert. These are what are provided in `labels.txt`.

What do the labels `0, 0.5, 1` mean (assuming the above is the case). Is 0 no relationship, or a negative relationship, or something else? It is not obvious to me from an attempt to parse the data.

**Comment by sujunhao** [comment]
Hi, thanks for your question.

1. Yes, in the abstract dataset, i.e., abs_data/1st_ann, gene and disease annotation are extracted from abstracts.

2. Please note that the gene-disease annotation in our dataset is in **document level** but not in sentence level, i.e., In the abstract dataset, like abs_data/1st_ann,  If an **abstract** contains both a gene and a disease, the relationship will be annotated as either 0, 0.5, 1 by an expert (based on the content of abstract). And yes, they are provided in labels.txt.

0 mean no relationship. For your information, I attached some descriptions of labelling from our note:

> An associated relation (labeled as 1) is defined as a pair of gene and disease that has a sort of association, including but not limited to cause, effect, existence, and regulation, either positive or negative, as written by the authors.
> 
> Non-associated relation (labeled as 0) is defined as a pair of gene and disease that the authors have semantically said nothing about.
> 
> Ambiguous association (labeled as 0.5) is defined as an uncertain association between a gene and a disease, which are difficult for an expert to decide (because they may be “Semantically Ambiguous” or “Incomprehensible”).

Regards,
Junhao

**Comment by jambo6** [comment]
I see, thanks, makes sense now.

Thats a serious dataset you've curated, kudos!
