### ISSUE TITLE
HELP,Please

### ISSUE THREAD

**Issue by goldjunkrat** [sujunhao/RENET2#4]
Hello,
1.I was wondering if I could use the entities identified by my own model as input and then use your tool to identify the entity relationships?
2.If so, could you please tell me the format of the input file?

**Comment by sujunhao** [comment]
Hi, 

Yes, and RENET2 requires the input documents alongside their annotations to be kept in {docs.txt, sentences.txt, anns.txt, labels.txt} files.

One can easily convert the Putator's ([reference 1](https://www.ncbi.nlm.nih.gov/research/pubtator/api.html), [reference 2](https://www.ncbi.nlm.nih.gov/CBBresearch/Lu/Demo/tmTools/Format.html)) pubtator (for abstract) and json (for full text) file into RENET2 required format by using the `renet2 parse_data` function. You can check the [pipeline example](https://github.com/sujunhao/RENET2#pipeline-use-renet2-to-predict-gene-disease-associations-from-articles-id) for more details. The example files of {docs.txt, sentences.txt, anns.txt, labels.txt} will be available at `${R2_DIR}/data/test_data` if you follow the pipeline example.

For using your in-house abstract data, the most convenient way is (1) save your information in the pubtator format, see [Tool-specific output format 1 (PubTator)](https://www.ncbi.nlm.nih.gov/CBBresearch/Lu/Demo/tmTools/Format.html), and (2) then use the `renet2 parse_data` function to parse to the format RENET2 wanted.
For using full-text data, you may need to write your own script to parse your data.

**Comment by goldjunkrat** [comment]
thanks a lot.
But my identification result is only the entity name and entity type, if converted to the format of Pubtator, then how to fill in the data in the entity information

**Comment by sujunhao** [comment]
Hi, the input of RENET2 is normally generated from two parts: (1) article text; (2) entity information, including the entity name, type (gene or disease), entity ID, and entity positions in the text. 

For the entity ID, you can use the same ID schema with RENET2, i.e. diseases are marked with [MESH ID](https://meshb.nlm.nih.gov/), genes are marked with [NCBI gene ID](https://www.ncbi.nlm.nih.gov/gene?Db=gene&Cmd=DetailsSearch&Term=8622), or using your own ID schema (marking your entity with ID like gene_1, gene_2.., , disease_1, disease_2, etc). 

thanks.

**Comment by goldjunkrat** [comment]
Ok,thank you very much,its really be helpful!
Have a good day ! Sir

**Comment by goldjunkrat** [comment]
I am sorry to disturb you again. And One More Thing,
Why is the relationship coefficient of the same pair of genetic diseases in the same article different when I annotate all the identified entities to the input file and when I annotate only part of the entities

**Comment by sujunhao** [comment]
Yes, it will have a different score predicted when having different annotations for text. For each prediction, RENET2 relies on the annotation for a **target** gene and disease pairs as well as **all other** gene and disease annotations in text. RENET2 has a different encoding for its neural network to utilize all annotations information in the text, including target annotations and other entities. We recommend including all genes and disease annotations in text for RENET2 to get accurate results.
Hope this answer your question.

thanks.

**Comment by sujunhao** [comment]
Closing it due to inactivity, please reopen it if you have more queries.
